version: 0.2

env:
  secrets-manager:
    LOGIN: jewelBox_x23355824:LOGIN
    HOST: jewelBox_x23355824:HOST
    Organization: jewelBox_x23355824:Organization
    Project: jewelBox_x23355824:Project

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - yum install -y jq curl
      - echo "Installed Java $(java -version 2>&1 | head -1)"

  build:
    commands:
      - |
        echo "=== Checking SonarQube Quality Gate ==="
        response=$(curl -sS -u "$LOGIN:" "$HOST/api/qualitygates/project_status?projectKey=$Project")
        status=$(echo "$response" | jq -r '.projectStatus.status')

        echo "Quality Gate Status: $status"
        echo "$response" | jq '.projectStatus.conditions[] | "  - \(.metricKey): \(.status) (Actual: \(.actualValue), Threshold: \(.errorThreshold))"'

        if [ "$status" = "ERROR" ]; then
          echo "❌ Critical: Quality Gate failed - Deployment blocked"
          exit 1
        elif [ "$status" = "OK" ]; then
          echo "✅ Success: Quality Gate passed"
        else
          echo "⚠️ Warning: Unknown status '$status'"
          exit 1
        fi