version: 0.2
env:
  secrets-manager:
    DJANGO_SECRET_KEY: jewelBox_x23355824:DJANGO_SECRET_KEY
    DB_PASS: jewelBox_x23355824:DB_PASS

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      # Install dependencies needed for running the static analysis 
      - pip install -r requirements.txt
  pre_build:
    commands:
      - python --version
      - echo "=== Setting up environment ==="
      - export DJANGO_SETTINGS_MODULE="jewelBox.settings.prod"
      - echo "DJANGO_SECRET_KEY=\"$DJANGO_SECRET_KEY\"" > .env
      - echo "DB_PASS=\"$DB_PASS\"" >> .env
      - echo "DJANGO_DEBUG=False" >> .env
      
artifacts:
  files:
    - '**/*'