version: 0.2
phases:
  install:
    runtime:
      python: 3.9
      java: corretto17
    commands:
      - yum update -y
      - yum install -y jq unzip
      - python -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - chmod +x sonar-scanner-5.0.1.3006-linux/bin/*
      - export PATH=$PATH:$PWD/sonar-scanner-5.0.1.3006-linux/bin

  pre_build:
    commands:
      - python --version
      - java -version
      - sonar-scanner --version
      - pylint --exit-zero frontEnd jewelBoxDbServices jewelBox

  build:
    commands:
      - echo "Waiting for SonarCloud automatic analysis to complete..."
      - sleep 10
      - echo "Checking Quality Gate status..."
      - curl -u "$LOGIN:" "$HOST/api/qualitygates/project_status?projectKey=$Project" > result.json
      - cat result.json
      - |
        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
          echo "❌ Quality Gate failed"
          exit 1
        else
          echo "✅ Quality Gate passed"
        fi

  test:
    commands:
      - source venv/bin/activate
      - pytest --maxfail=3 --disable-warnings -q

artifacts:
  files:
    - '*/'