version: 0.2
env:
  secrets-manager:
    DJANGO_SECRET_KEY: jewelBox_x23355824:DJANGO_SECRET_KEY
    DB_PASS: jewelBox_x23355824:DB_PASS

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      # Install dependencies needed for running the static analysis
      - pip install -r requirements.txt
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - chmod +x sonar-scanner-5.0.1.3006-linux/bin/*
      - export PATH=$PATH:$PWD/sonar-scanner-5.0.1.3006-linux/bin
  pre_build:
    commands:
      - python --version
      - pylint --exit-zero frontEnd jewelBoxDbServices jewelBox
      - echo "=== Setting up environment ==="
      - export DJANGO_SETTINGS_MODULE="jewelBox.settings.prod"
      - echo "DJANGO_SECRET_KEY=\"$DJANGO_SECRET_KEY\"" > .env
      - echo "DB_PASS=\"$DB_PASS\"" >> .env
      - echo "DJANGO_DEBUG=False" >> .env
  build:
    commands:
      - echo "Waiting for SonarCloud automatic analysis to complete..."
      - sleep 10
      - echo "Checking Quality Gate status..."
      - curl -u "$LOGIN:" "$HOST/api/qualitygates/project_status?projectKey=$Project" > result.json
      - cat result.json
      - |
        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
          echo "❌ Quality Gate failed"
          exit 1
        else
          echo "✅ Quality Gate passed"
        fi
      
artifacts:
  files:
    - '**/*'