version: 0.2
phases:
  test:
    commands:
      - source venv/bin/activate
      - pytest --maxfail=3 --disable-warnings -q
      - pylint --exit-zero frontEnd jewelBoxDbServices jewelBox

artifacts:
  files:
    - '*/'
