version: 0.2
env:
  secrets-manager:
    LOGIN: jewelBox_x23355824:LOGIN
    HOST: jewelBox_x23355824:HOST
    Organization: jewelBox_x23355824:Organization
    Project: jewelBox_x23355824:Project
    DJANGO_SECRET_KEY: jewelBox_x23355824:DJANGO_SECRET_KEY

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      # Install dependencies needed for running the static analysis
      - pip install -r requirements.txt pylint
      - pip install python-dotenv
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-*.zip
      - rm sonar-scanner-*.zip
      - mv sonar-scanner-* sonar-scanner
      - export PATH=$PATH:$PWD/sonar-scanner/bin
  pre_build:
    commands:
      - echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" > .env
      - echo "DEBUG=False" >> .env
      - python --version
      - pylint --exit-zero frontEnd jewelBoxDbServices jewelBox
  build:
    commands:
      - echo "Waiting for SonarCloud automatic analysis to complete..."
      - sleep 10
      - echo "Checking Quality Gate status..."
      - curl -u "$LOGIN:" "$HOST/api/qualitygates/project_status?projectKey=$Project" > result.json
      - cat result.json
      - |
        if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
          echo "❌ Quality Gate failed"
          exit 1
        else
          echo "✅ Quality Gate passed"
        fi
artifacts:
  files:
    - '**/*'
