# Generated by Django 5.1.7 on 2025-03-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelBoxDbServices', '0002_alter_customuser_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='category',
            field=models.CharField(choices=[('Necklace', 'Necklace'), ('Earrings', 'Earrings'), ('Bracelet', 'Bracelet'), ('Ring', 'Ring')], default='Uncategorized', max_length=20),
        ),
    ]
