# Generated by Django 5.1.7 on 2025-04-03 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelBoxDbServices', '0003_jewelry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Phone number must be exactly 10 digits.'), django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must contain only digits.')]),
        ),
    ]
