# Generated by Django 5.1.7 on 2025-03-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelBoxDbServices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ring', 'Ring'), ('necklace', 'Necklace'), ('bracelet', 'Bracelet'), ('earring', 'Earring'), ('watch', 'Watch')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jewellery_images/')),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
