# Generated by Django 5.1.7 on 2025-03-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelBoxDbServices', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_owner',
        ),
    ]
