# Generated by Django 5.1.7 on 2025-03-17 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jewelBoxDbServices', '0005_remove_customeruser_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerUser',
            new_name='Customer',
        ),
    ]
